# Домашнее задание № 1 по курсу "ML для старта в Data Science"

В задании используется открытый датасет Wine Quality (Red Wine) – показатели химического состава португальского красного вина “Vinho Verde” и оценки его качества. Датасет содержит 1599 образцов красного вина и 12 признаков: 11 числовых физико-химических характеристик вина (кислотность, содержание сахара, pH, сульфиты и др.) и качество – итоговая оценка от 0 до 10 (целевой признак). Каждый экземпляр данных представляет одно вино, качество которого определено как медиана оценок нескольких экспертов (целое число от 0 до 10). 

Признаки (X):
- fixed acidity – фиксированная кислотность (г/дм³)
- volatile acidity – летучая кислотность (уксусная кислота, г/дм³)
- citric acid – лимонная кислота (г/дм³)
- residual sugar – остаточный сахар (г/дм³)
- chlorides – хлориды (соль, г/дм³)
- free sulfur dioxide – свободный диоксид серы (мг/дм³)
- total sulfur dioxide – общий диоксид серы (мг/дм³)
- density – плотность (г/см³)
- pH – кислотность (pH)
- sulphates – сульфаты (г/дм³)
- alcohol – содержание алкоголя (% об.)

Целевой признак:
- quality – оценка качества вина (целое число от 0 до 10)

*В этом задании мы закрепим навыки первых трёх тем:*
* предобработаем и проанализируем данные
* найдём и обработаем мультиколлинеарность
* попрактикуемся в работе с линейной регрессией
* разберёмся с проблемами переобучения
* применим регуляризацию для повышения качества и обобщающей способности модели

#### Критерии оценивания:

| Задание    | Балл |
| ---------- | ---- |
| Задание 1  | 15   |
| Задание 2  | 15   |
| Задание 3  | 15   |
| Задание 4  | 15   |
| Задание 5  | 20   |
| Задание 6  | 20   |

**Суммарно 100 баллов за задание.**

In [1]:
# здесь импортируем нужные библиотеки и модели,
# добавляйте в ячейку всё, что потребуется:)

import pandas as pd

## Задание 1
Первым делом **познакомимся с данными**, а заодно закрепим методы работы с Pandas.

- Проверьте наличие пропусков в данных и при необходимости обработайте их.  
- Проверьте наличие выбросов и при необходимости почистите их.
- Проверьте наличие дубликатов и при необходимости почистите их.
- Подумайте, есть ли в данных неинформативные признаки, при необходимости удалите их.
- Запишите наблюдения в виде небольшого вывода.

In [5]:
# чтение данных
data = pd.read_csv('winequality-red.csv', header=0, sep=';')

print(data.shape)
data.head()# место для кода

(1599, 12)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [7]:
data.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

Несколько записей по поводу данных:
- 1599 образцов с 11 признаками и 1 таргетом в последнем столбце
- относительно большие отклонения от среднего и 75% квантиля имеются для: residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide (проверить на выбросы)

In [13]:
X = data.drop('quality', axis=1)
feature_names = X.columns

y = data['quality']

# X.head()
# y.head()

df = pd.DataFrame(X, columns=feature_names)
df["target"] = y
print(df.shape)
df.head()

(1599, 12)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,target
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [14]:
df.info() # info для проверки наличия пропусков в данных

<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  target                1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

<место для интересных выводов и рассуждений!>

## Задание 2

Проведём небольшой **EDA.**

- Посмотрите на распределение целевого признака `extr_per_day`.
- Изучите распределения остальных признаков, а также парные зависимости (можете воспользоваться `pairplot` либо построить графики по отдельности).
- Постройте матрицу корреляций, визуализируйте её и проанализируйте наличие мультиколлинеарных признаков (в качестве порога можно взять ±0.7).
- Зафиксируйте наблюдения в небольшом выводе.

In [ ]:
# место для кода

In [ ]:
# место для кода

In [ ]:
# место для кода

<место для интересных выводов и рассуждений!>

## Задание 3

**Финально подготовим данные для модели.**

* По итогам EDA удалите сильно скоррелированные признакие, если они нашлись; а также выбросы/ошибочные записи - всё, что посчитаете нужным.
* Создайте матрицу признаков `X` и вектор таргета `y`, *не забудьте добавить столбец "свободных членов" из единиц в матрицу `X`, чтобы использовать её в собственноручно написанных алгоритмов*.
* Разбейте данные на тренировочную и тестовую выборку, установите соотношение 80/20 и random_state=42.
* Выберите подходящий способ масштабирования или нормализации данных; примените его для датасета - не забудьте, что на тестовой выборке необходимо выполнить только трансформирование.
* Зафиксируйте выполненные преобразования в текстовом виде в конце.

In [ ]:
# место для кода

In [ ]:
# место для кода

In [ ]:
# место для кода

<место для интересных выводов и рассуждений!>

## Задание 4

**Приступаем к моделированию!**

* Первым делом предлагаем построить модель линейной регрессии по МНК: попробуйте воспользоваться ручной реализацией ~со 2-го занятия~ и сравнить результат с `LinearRegression` из `sklearn`.
* Оцените модель по метрикам MSE, MAE и MAPE на тренировочной и тестовой выборках ~(можно воспользоваться реализацией с занятия)~. Проанализируйте полученные метрики - насколько модель хорошо предсказывает результат?
* Напишите небольшой вывод касательно полученных результатов.

In [ ]:
# место для кода

In [ ]:
# место для кода

In [ ]:
# место для кода

<место для интересных выводов и рассуждений!>

## Задание 5

**Попробуем усложнить.**

* Выберите не менее 3-х вариаций градиентного спуска и обучите их на имеющихся данных. Интересно "поиграться" с гиперпараметрами шага, количества итераций и т.п. Попробуйте получить как можно более высокое качество алгоритма.
* Постройте для каждого эксперимента график сходимости и также оцените модель по метрикам MSE, MAE и MAPE.
* Напишите небольшой вывод - удалось ли улучшить прогноз?

In [ ]:
# место для кода

In [ ]:
# место для кода

In [ ]:
# место для Вашего прекрасного кода

<место для интересных выводов и рассуждений!>

## Задание 6

А что, если бы мы не стали удалять никакие признаки, а просто сразу применили бы **регуляризацию**? Попробуйте в рамках этого задания:
* Взять данные без удаления мультиколлинеарных признаков и обучить на них лучший алгоритм, который Вам удалось выявить в предыдущих заданиях, *без регуляризации*. Посмотрите, как ведут себя метрики на тренировочном и тестовом наборе, а также какие веса у модели.
* Взять данные без удаления мультиколлинеарных признаков и обучить на них лучший алгоритм, который Вам удалось выявить в предыдущих заданиях, *с L1 и L2 регуляризацией* по отдельности. Сравните метрики и веса с прошлым вариантом, а также с полученными результатами в 4-5 заданиях.
* Что лучше: обучиться на всех данных с регуляризацией или превентивно устранять мультиколлинеарность? Для самой наилучшей модели определите, какие признаки наиболее важны при прогнозировании. Отразите итоговые рекомендации в выводе.

In [ ]:
# место для кода

In [ ]:
# место для кода

In [ ]:
# место для кода

<место для интересных выводов и рассуждений!>

## 🎉 Всё получилось?
Когда решите, что сделали всё возможное - присылайте задание нам на проверку 😊

Достаточно будет ссылки на colab-ноутбук, **самое главное - проверьте, что открыли доступ к файлу!**